FROM golang:1.13 as builder

COPY ./src/ /work
WORKDIR /work
RUN GOOS=linux go build --ldflags '-linkmode external -extldflags -static'

FROM ubuntu:18.04
COPY --from=builder /work/maestro .
CMD ["./maestro"]
